[graph]
exclude-unpublished = true

[advisories]
unmaintained = "none"
ignore = []

[licenses]
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BUSL-1.1",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",


]

[bans]
multiple-versions = "deny"
highlight = "all"
skip-tree = [
    { name = "windows_x86_64_msvc" },
    { name = "windows_x86_64_gnullvm" },
    { name = "windows_x86_64_gnu" },
    { name = "windows-targets" },
    { name = "windows-sys" },
    { name = "windows-result" },
    { name = "windows-interface" },
    { name = "windows-implement" },
    { name = "windows_i686_msvc" },
    { name = "windows_i686_gnullvm" },
    { name = "windows_i686_gnu" },
    { name = "windows-core" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_aarch64_gnullvm" },
    { name = "vart" },
    { name = "thiserror-impl" },
    { name = "thiserror" },
    { name = "revision-derive" },
    { name = "revision" },
    { name = "rand_core" },
    { name = "rand_chacha" },
    { name = "rand" },
    { name = "quick_cache" },
    { name = "itertools" },
    { name = "indexmap" },
    { name = "darling_macro" },
    { name = "darling_core" },
    { name = "darling" },
    { name = "base64" },
    { name = "approx" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-git = []

[[licenses.clarify]]
name = "surrealdb"
expression = "BUSL-1.1"
license-files = []

[[licenses.clarify]]
name = "surrealdb-core"
expression = "BUSL-1.1"
license-files = []
